import "./globals.css";
import { Work_Sans } from "next/font/google";
import classNames from "classnames";
import { Navigation } from "@/components/layout";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark h-full">
      <body className={classNames(workSans.className, "h-full")}>
        <div className="min-h-full">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
